secrets:
    hostname: ENC[AES256_GCM,data:dIVy/YkIOitpZedDki9ROLw=,iv:tOJk3aRqnwVRf3M+9WMAa1THEriV1+IYpVmrllX13QM=,tag:lDuaFOds5RNd/CBMQpLL5Q==,type:str]
    env:
        OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:g9I3QufHe5sM8oLv0RomzLfGL71tfS3p729YMem0I3z1N+60YMBRVcJlJHA=,iv:o9NMTFeKhoMXAOvL4xE/4FvM+xnxuy6dZGz8bQ9K4fs=,tag:iIhktMtwU0YVC0C/34yivw==,type:str]
sops:
    age:
        - recipient: age1wjnx0ggpvkk9aufyu2juzc7fvlgcefxx5ngn5hsae5n5vl47fcaqzstuf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaUFtTDZkem5xaVJ5aW1m
            ZnRmZVd5YWlQeENNVGpSMVBOYmV0d2R2c1hRCjQ4eDlISSswSlR6RnRGT0xGN0pQ
            dnBPR1orWllxKzRqb01yYTJsZVZLTUkKLS0tIER2UVJQRVNyY1J1bkMrYmlsV1M2
            aGUyeENONGxuSWZ5Y3VKL0o2Ym8rczgKj7yn4i0ulpoJ7UA1+YArhSxu6r6O4wZx
            AAR7Ftv2ZHnVtYoNVkh554j2IY9H/Y+kp6YGIGTyk/GIMMnbbKn9Hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eyjyp4n5ke066nkgcxkqmkzl50nlwkdufsm2qzz5rfvc7peelc5qlnufz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZjJJYVpYeHd2bTRJeGor
            dUdGTDV5VFpFeCtkeDdTajBFdUtycUdDQ2hrCmlhTndNUEFYTmtpV1FUUnlmY2pi
            cXFnd1hNSmk4VXh5RHBwUWR1L0NZSVUKLS0tIEhLanRZdXdWTUs4MHJOSERpUkZw
            Z3hoSFprUWFnbkVrTmpGQ05rSUQzcHcKFB4DSicwRkxqNn9Ebexli1gPeEbVBay6
            FCQ9OYZ0Lmfak0MXFm5mQOJSHE94i4hvNi8djykdcjemi1LRqR0oGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueXBvbkV4SDJRK1VhalpE
            MmhOdWd5MDJwaFRUQUVGMWxMcUNocHQrTzM0ClN1UXErZHVYOElndEoxYy9ZQ3Q4
            RFFITmYzYk1ZOERaVS9LNVNhMWZjWHMKLS0tIENnN0gwUlhnQ3BROXVlc3ljRFRI
            WU1leUdHbFBld0ptR1Y1V1JDNE1TbVkKUZVczMpBn9O7bqC2Np+k6evDgFhUC56+
            0WajpbNsJUE/XPeGRxyPUgPQoh6FV0+umJx2DWIDvgYywUEL/0PAwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T08:26:20Z"
    mac: ENC[AES256_GCM,data:E1NWsTIuTUkEP9J7w7VgZp+mP+XGk55kloQdk97FQa9rVA/zECkdOBd0WwP+daDPluB6zoZznHgISVsUNCCvwTJMGZEbGk6R4eMeC8tMmtetYqU7cMF/XtKas3Q4YugV5BhG09MCVoczT1bqSeIcfsQISMsInrk0dE7/SEBIDA8=,iv:61IzAsyzSWDSpoCzsjP3ua5qJw8qkoE3fNNyHvYd31o=,tag:p9Np+SS4Rx/QKm++pQDsFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
