keys:
  - &kang_macbook_air age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
  - &stay_raspberrypi age1xf07v5cv2zdrevmv5mfwen8jhg8nu2gkl7sr0j04gdkyfqlr2fcqk9qwze
  - &home_nixos age1de0nqv36jzggd5xrhevff4w6w5772qgey3xhnru825z2l748hanse7nw55
  - &stay_nixos age1eyjyp4n5ke066nkgcxkqmkzl50nlwkdufsm2qzz5rfvc7peelc5qlnufz7
  - &stay_gmk age1wjnx0ggpvkk9aufyu2juzc7fvlgcefxx5ngn5hsae5n5vl47fcaqzstuf5
  - &kang_rpi age10vsknp7hlnnw6hndrqhzv5wd3u2ucp888du5lmykamext6lzn3jqmjgstu
  - &kang_oddesey age1j9gx54ya0y9d0erh8u2rpgckwlvcxdjcsa6xkddnsyq7gaam5p7sq87p7n
creation_rules:
  - path_regex: stay_secrets.yaml$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: client.ovpn$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
        - *home_nixos
  - path_regex: stay_router_user_pass.txt$
    key_groups:
      - age:
        - *home_nixos
  - path_regex: hosts/rpi4/renew_duckdns.sh$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: hosts/rpi4/Caddyfile$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: hosts/rpi4/vaultwarden_env$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: hosts/kang_macbook_air/env$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: hosts/rpi4/transmission_env$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: hosts/rpi4/supabase_env$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: hosts/rpi4/librechat_env$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: hosts/rpi4/opengpts_env$
    key_groups:
      - age:
        - *kang_macbook_air
        - *stay_raspberrypi
  - path_regex: hosts/kang_oddesey/wpa_supplicant_secret
    key_groups:
      - age:
        - *kang_oddesey
  - path_regex: smb_credential.txt$
    key_groups:
      - age:
        - *home_nixos
        - *stay_nixos
        - *kang_macbook_air
  - path_regex: k3sCluster/tokenfile$
    key_groups:
      - age:
        - *stay_gmk
        - *stay_nixos
        - *kang_macbook_air
        - *kang_rpi
  - path_regex: k3sCluster/charts/.*/.*-?secrets\.yaml$
    key_groups:
      - age:
        - *stay_gmk
        - *stay_nixos
        - *kang_macbook_air
  - path_regex: k3sCluster/wg_external_private_key$
    key_groups:
      - age:
        - *stay_gmk
        - *stay_nixos
        - *kang_macbook_air
        - *kang_rpi
  - path_regex: k3sCluster/wg_vxlan_private_key$
    key_groups:
      - age:
        - *stay_gmk
        - *stay_nixos
        - *kang_macbook_air
        - *kang_rpi
  - path_regex: keys/.*\_age_key.txt$
    key_groups:
      - age:
        - *kang_macbook_air
