repositories:
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard
- name: nfs-subdir-external-provisioner
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
- name: traefik
  url: https://traefik.github.io/charts

releases:
- name: traefik
  namespace: traefik
  chart: traefik/traefik
  values:
  - ./traefik_values.yaml
- name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
- name: kubernetes-dashboard-config
  namespace: kubernetes-dashboard
  chart: ./charts/kubernetes-dashboard-config
- name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
  chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
  set:
  - name: nfs.server
    value: 192.168.219.150
  - name: nfs.path
    value: /nfs
- name: adguard
  namespace: adguard
  chart: ./charts/adguardhome
  values:
    - ./charts/adguardhome/values.yaml
  needs:
    - traefik/traefik
- name: samba-transmission
  namespace: samba-transmission
  chart: ./charts/samba-transmission
  values:
    - ./charts/samba-transmission/values.yaml
  secrets:
    - ./charts/samba-transmission/secrets.yaml
- name: vaultwarden
  namespace: vaultwarden
  chart: ./charts/vaultwarden
  values:
    - ./charts/vaultwarden/values.yaml
  secrets:
    - ./charts/vaultwarden/secrets.yaml
