repositories:
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard
- name: nfs-subdir-external-provisioner
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
- name: traefik
  url: https://traefik.github.io/charts
- name: jetstack
  url: https://charts.jetstack.io
- name: emberstack
  url: https://emberstack.github.io/helm-charts
- name: blue-atlas
  url: https://charts.blue-atlas.de
- name: bitnami
  url: https://charts.bitnami.com/bitnami


releases:
- name: traefik
  namespace: traefik
  chart: traefik/traefik
  values:
  - ./traefik_values.yaml
- name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
- name: kubernetes-dashboard-config
  namespace: kubernetes-dashboard
  chart: ./charts/kubernetes-dashboard-config
- name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
  chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
  set:
  - name: nfs.server
    value: 192.168.219.150
  - name: nfs.path
    value: /nfs
  - name: nodeSelector.current-mode
    value: primary
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  set:
    - name: crds.enabled
      value: true
    - name: prometheus.enabled
      value: false
- name: reflector
  namespace: reflector
  chart: emberstack/reflector
- name: cert-manager-config
  namespace: cert-manager-config
  chart: ./charts/cert-manager-config
  secrets:
    - ./charts/cert-manager-config/secrets.yaml
  needs:
    - cert-manager/cert-manager
    - reflector/reflector
- name: adguard
  namespace: adguard
  chart: ./charts/adguardhome
  values:
    - ./charts/adguardhome/values.yaml
  needs:
    - traefik/traefik
- name: samba-transmission
  namespace: samba-transmission
  chart: ./charts/samba-transmission
  values:
    - ./charts/samba-transmission/values.yaml
  secrets:
    - ./charts/samba-transmission/secrets.yaml
  needs:
    - traefik/traefik
- name: vaultwarden
  namespace: vaultwarden
  chart: ./charts/vaultwarden
  values:
    - ./charts/vaultwarden/values.yaml
  secrets:
    - ./charts/vaultwarden/secrets.yaml
  needs:
    - traefik/traefik
- name: duckdns
  namespace: duckdns
  chart: ./charts/duckdns
  secrets:
    - ./charts/duckdns/secrets.yaml
  needs:
    - traefik/traefik
- name: librechat-config
  namespace: librechat
  chart: ./charts/librechat
  values:
    - ./charts/librechat/values.yaml
  secrets:
    - ./charts/librechat/secrets.yaml
  needs:
    - traefik/traefik
- name: librechat
  namespace: librechat
  chart: blue-atlas/librechat
  values:
    - ./charts/librechat/values.yaml
    - ./charts/librechat/values.gotmpl
  secrets:
    - ./charts/librechat/secrets.yaml
  needs:
    - librechat-config
- name: cookie-based-routing-index
  namespace: cookie-based-routing-index
  chart: ./charts/cookie-based-routing-index/
  secrets:
    - ./charts/cookie-based-routing-index/secrets.yaml
  values:
    - ./charts/cookie-based-routing-index/values.yaml
  needs:
    - traefik/traefik
- name: postgres-for-n8n
  namespace: n8n
  chart: bitnami/postgresql
  values:
    - ./charts/n8n/values_postgres.yaml
  secrets:
    - ./charts/n8n/secrets.yaml
- name: n8n
  namespace: n8n
  chart: oci://8gears.container-registry.com/library/n8n
  version: 1.0.15
  values:
    - ./charts/n8n/values.yaml
  secrets:
    - ./charts/n8n/secrets.yaml
  needs:
    - traefik/traefik
    - postgres-for-n8n
- name: n8n-config
  namespace: n8n
  chart: ./charts/n8n
  needs:
    - n8n
