
deployment:
  kind: DaemonSet

ports:
  web:
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/8
    proxyProtocol:
      trustedIPs:
        - 10.0.0.0/8
  websecure:
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/8
    proxyProtocol:
      trustedIPs:
        - 10.0.0.0/8
    http3:
      enabled: true
      advertisedPort: 443

ingressRoute:
  dashboard:
    enabled: true

service:
  single: false
  type: NodePort
  externalIPs:
    - 192.168.219.104
    - 192.168.219.114
    - 192.168.219.150
  spec:
    externalTrafficPolicy: Local

logs:
  access:
    enabled: true
