
deployment:
  kind: DaemonSet

ports:
  web:
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/8
    proxyProtocol:
      trustedIPs:
        - 10.0.0.0/8
  websecure:
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/8
    proxyProtocol:
      trustedIPs:
        - 10.0.0.0/8
  dns-tcp:
    port: 8053
    expose:
      default: true
    exposedPort: 53
    tls:
      enabled: false
  dns-udp:
    port: 8054
    expose:
      default: true
    exposedPort: 53
    protocol: UDP
  smb:
    port: 445
    expose:
      default: true
    exposedPort: 445
    protocol: TCP
    tls:
      enabled: false
  mission-tcp:
    port: 51413
    expose:
      default: true
    exposedPort: 51413
    protocol: TCP
    tls:
      enabled: false
  mission-udp:
    port: 51413
    expose:
      default: true
    exposedPort: 51413
    protocol: UDP

service:
  single: false
  type: NodePort
  externalIPs:
    - 192.168.219.104
    - 192.168.219.114
    - 192.168.219.150
  spec:
    externalTrafficPolicy: Local
