secret:
  files:
    index.html: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <title>Set Route Cookie</title>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
              .set-route {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100dvh;
              }
      
              .set-route button {
                padding: 10px 20px;
                margin: 10px;
                font-size: 16px;
                cursor: pointer;
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                transition: background-color 0.3s ease;
              }
      
              .set-route button:hover {
                background-color: #0056b3;
              }
          </style>
      </head>
      <body class="set-route">
          <button onclick="setCookie('app_route', 'librechat')">Go to LibreChat</button>
          <button onclick="setCookie('app_route', 'other')">Go to Other</button>
          
          <script>
          function setCookie(name, value, days) {
            let expires = "";
            if (days) {
              let date = new Date();
              date.setTime(date.getTime() + (days*24*60*60*1000));
              expires = "; expires=" + date.toUTCString();
            }
            document.cookie = name + "=" + (value || "")  + expires + "; path=/";
            window.location.replace("/");
          }
          </script>
      </body>
      </html>
    set-route.html: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <title>Set Route Cookie</title>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
              .set-route {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100dvh;
              }
      
              .set-route button {
                padding: 10px 20px;
                margin: 10px;
                font-size: 16px;
                cursor: pointer;
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                transition: background-color 0.3s ease;
              }
      
              .set-route button:hover {
                background-color: #0056b3;
              }
          </style>
      </head>
      <body class="set-route">
          <button onclick="setCookie('app_route', 'librechat')">Go to LibreChat</button>
          <button onclick="setCookie('app_route', 'other')">Go to Other</button>
          
          <script>
          function setCookie(name, value, days) {
            let expires = "";
            if (days) {
              let date = new Date();
              date.setTime(date.getTime() + (days*24*60*60*1000));
              expires = "; expires=" + date.toUTCString();
            }
            document.cookie = name + "=" + (value || "")  + expires + "; path=/";
            window.location.replace("/");
          }
          </script>
      </body>
      </html>


