librechat:
    secrets:
        CREDS_KEY: ENC[AES256_GCM,data:jK7CitFg4xL13gdsc+oGwa+ypDI6c3oYLtyy89zQE05Uzi+g0YzVhCSq6n7TdrNnkEVLhi2lB4Ln6atDWQkxMQ==,iv:nbf0s1KFYlb2Y3tZR3Z9J+mUzZ77Vb8IK9FeXh3xg6Q=,tag:qarM2hvnj8hGkFU4GGvS7Q==,type:str]
        CREDS_IV: ENC[AES256_GCM,data:y4+UiIG6rjYI2zmSQ2t0x3g5vSXFRyLnU7M893cwPNE=,iv:1YDX7KeWqLys9EA40E0tidM7au1M/MoFtPZtDxXhENo=,tag:Xiee202iawX64PzQEmmYbA==,type:str]
        JWT_SECRET: ENC[AES256_GCM,data:z7jOhbUGoPgZqFWGx/PKSMDo0XAZRlKrtSnGWqyh3OL9ypLtQv/XqfizxacwDdheQV8jmCqQv2TNjH0t7dlELg==,iv:uePnskmdz+ODSkhcDbQngsVX+jutazY8z+6SCSK677k=,tag:rCvZcQcOVMUFkNAgiHnLjw==,type:str]
        JWT_REFRESH_SECRET: ENC[AES256_GCM,data:BxSDA/zLvbAeGRoPOQkmsNZFgamX4XfpQM+PB0u6XExlVzvbl5L4gUARpB+cjty5SpOkO16KYNRyuaXT4nXiJA==,iv:F53cGpV6bTz/li6t04ARixcdZZvBDPLg6iY8FeMGhUo=,tag:A/6VvIPMfNALTSgUEw9H/A==,type:str]
        MEILI_MASTER_KEY: ENC[AES256_GCM,data:qT0yo6bESX80yqwt/clZLe5o4KC2ZrAAdFnIzHavsa9jOHenCjBQ+ZtmitWbiUdV20e83LXd1ePYqdvMUGHV0g==,iv:8k9dAOPPtU/Ugw0d5lDY/7Zo+wXTO5UujeXRmhqEtvo=,tag:eJDmbdfh7KaR8IQONpTWsw==,type:str]
        OPENAI_API_KEY: ENC[AES256_GCM,data:tK52Y9TSCC4Y7Y2N+c4YrKqGCM1WsnSN24IzcZ9MAX44nJw3+4a+NKzlXdd8VIT3FlHi1CKFndMabHh1YXCtRUuCdTp1okX5RjTG0AyYmgdhcocKHUZvZLmIfI9npYSKTquVYVcNRgo7olOtwj5COCb2apJ59cD9ve8SQw4VqJFwDEB6x5Dx29Y2si5a8MMiZ2+/KYOxISmgWPAQ4gNWBs96nLU=,iv:U/3vKS34KcLnR6FKQ/QWxtp5vkMvbslrfYKCDKQ8Uhw=,tag:w6jMoGcxJxCqHFY1aRT0SQ==,type:str]
        ANTHROPIC_API_KEY: ENC[AES256_GCM,data:OG3DaSNn7VFSReckD/QQCicowUkaAokc8r1WHjsCBOayRBm4WdQQLe5SDSHJCUlSHgNW2YQdsnoM/fSkwOSpXS2rxjEu9GGA4pBDYY+1iTK3YpYTNyiSNpqFz1dvgi56qgJT0jpAnzbfRCbU,iv:Ho8C3csPL/+fyAeRbDy1EVmwsy8T2YG3Fh6oD/ssR1g=,tag:Ws7fK9nV3jCMAAXL08JlBg==,type:str]
        GOOGLE_KEY: ENC[AES256_GCM,data:e+IYnlotVr3IW8mTxEKqFFJJAEL6dMMDoplq/s9hJEsWgSryvubk,iv:bWnIvOmWPFGFixvVMTokAM+HbndQtvV8tCR/IM5x7Wc=,tag:Gfib+6/h9vCpY40dIRf/Ng==,type:str]
        GOOGLE_EXCLUDE_SAFETY_SETTINGS: ENC[AES256_GCM,data:APjDWQ==,iv:O9UjFgpMwZQAtsgjUr7ClBG4Nw2PN/ZrhtXdE5iTYhc=,tag:1m1pAv+eSqCFv5CW+gtYEg==,type:str]
        GOOGLE_MODELS: ENC[AES256_GCM,data:ea3wH3PjgcfrOYNn0a/a0ASQUu/Zk+QyNB+3+SEd5pm+tHx++nE8Vxqvha9loP+YUHrUsLiLgapxM874ZXs8x96CZ69k4Wbvp2e4jLRRVtXyYo1FFhPqeLGYufvALfJrf9jTNTaC,iv:Y1w3YWYHuPSG5qSAQMBoNOJ55EpwRhdBPEe6eurm6w4=,tag:eSJ9SsfcKgTVGDfUPatZMA==,type:str]
mcp_servers:
    brave-search:
        secrets:
            BRAVE_API_KEY: ENC[AES256_GCM,data:BJowYtI4wlXS0Wdo9tTQyHsAlCKitGpH7J41ypiIGg==,iv:JAFG0TGquGsRMo1eT6jcDJFPcrervtZg5qkX57Zf4p0=,tag:RdSp/R6sg8ZzVprJFVTYQg==,type:str]
sops:
    age:
        - recipient: age1wjnx0ggpvkk9aufyu2juzc7fvlgcefxx5ngn5hsae5n5vl47fcaqzstuf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmb2pGYUJmTmZvdjZvUlMz
            b2hxK1gyeEQrZFNENUIzRGlOcG9qZmNTNFYwCnRETWRJNHNTdTBCSEE1UmtRWERZ
            YXZsRk5iNVNPM2FMWDQ0NzVCOUVuQ3MKLS0tIHFqSkFmVlhsMVdSdGh1RytuVm52
            eitDWndsc2drNVR1ZEhjZk9DVDNHOWMK6reT2tS/xQ4gHQWrUsdA2cJfTOQyYxAS
            0MeTmfG9BJ5cXfIN5I9AdtgAfPC+UVoWmeqC0haQArmf+Chr0n0z3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eyjyp4n5ke066nkgcxkqmkzl50nlwkdufsm2qzz5rfvc7peelc5qlnufz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRWpFRWk0Mk5hbmFhbVV2
            NU5QUHZCOHZ6aFZsNDNETDBZUDNTWUhqeXh3CjhlWHhPblpxNXpqRmFXNUg3RzR6
            UTFHQ2hoTVJtcFgwa09QK082TmF4WUUKLS0tIHVUVUlZVldybW9ya3hnd01BUEJY
            OTRwVWdKbU9uVkE5MkpyUlYwS0x5bWMKquPgcD89ffXJP8Mdmmfkc40RXTDX2iTK
            ZAQhxBI8mDa7D7R5V5kB3apLWgCIzE3rbCgzEN1/kpPG2QeBp80BVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K2NLRnFiNVBYdnB0a3ZI
            RURDcGR6cEJmY3VZN2ticGNjWFZ4a1EwRkcwClF5MEwvVlM2TXprZWtETzZiNW1V
            M0pMelVOVUdxdlFISWJmdHF4MVlISmsKLS0tIElhTmxrakxISm44SHJmQ2tmdmh3
            RHBUeGdzdmNmYTN4Y1Y2bXNhVk96NVkKwZRlQM2IECrttlrrSINxqOc0u5TcnPws
            hoz+s1pNMDMdFV+jooBZYhbn9rxKvdyZnyybP8bBOT4YQ7F9XcGU3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T06:23:08Z"
    mac: ENC[AES256_GCM,data:cbJ6vz3JBOVYYWC7QoS/9IuZji2hDkgkK71LJkcvr6HCoY1jKEVpQFtibBkJrWCfqSEvySF3AeoQ0NeCTRPil2ozFSluuOCMTHPyTvICpgzWiHRcuu1SizfWtJV44C9cNSEDY0gjrQ30OXh03v2D2BGANcYqljP9gF4kV8czrzA=,iv:QB7Qx6PaYavDvdXjntwp5mgnm/mvWsiWbCzUnvkXJts=,tag:k84PSrMmc22oEDSDIT7aGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
