apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: force-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
spec:
  entryPoints:
    - websecure
    - web
  middlewares:
    - name: force-https
      namespace: {{ .Release.Namespace }}
  routes:
    - match: (ClientIP(`192.168.219.0/24`) || ClientIP(`192.168.128.0/24`)) && Host(`{{ .Values.secrets.hostname }}`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 80
  tls:
    secretName: vaultwarden-certificate
