image:
  repository: docker.io/vaultwarden/server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

persistence:
  enabled: true
  storageClass: nfs-client
  size: 1Gi

envSecret: vaultwarden-env

