secrets:
    duckdns-environment:
        DUCKDNS_DOMAINS: ENC[AES256_GCM,data:+PnmBtKpWZwRqoxFaELfHok3Tys=,iv:PLE9M5XRmsU42euIO6vmJZN0mqroehRH9RLwZbi9nKs=,tag:Eoudt5NQ1qto7aV3GlkM0g==,type:str]
        DUCKDNS_TOKEN: ENC[AES256_GCM,data:uSqKfJcIexo95z8UnTwg9PZqdqfEjSLW9/tbgFUC1hJ9yrLl,iv:aEdkeJouKoYf1JB2hifKiTjlVuqglJsZGORo9PBlodo=,tag:cVRja5lIlTKMoTt4PPr8xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wjnx0ggpvkk9aufyu2juzc7fvlgcefxx5ngn5hsae5n5vl47fcaqzstuf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVTNQdzZ5cWYyVTM5d3B4
            RTZxV1NONUpyNHNqV2U1am5NMGdzQjRRaWswCkpuSFlyNHhPM1ZiaVQ0Nkx2K1lN
            RXRQaHRuQ0JScWlmazJUTkRLMlVySlUKLS0tIDRERUNTZlpYdFBOMlN3M1MraUdD
            QmkrMytqaklWZG9JZGZKd3BCZEpWeVUKj7X8UXRctAzN9vzeeiVO8r5IH0JEJQQp
            veFDesXdHa54FvAS4Ga4O0Ewwgz9yumOFad/3vGa359XJ0IvPXaEQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eyjyp4n5ke066nkgcxkqmkzl50nlwkdufsm2qzz5rfvc7peelc5qlnufz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NFdXUFNsMkhGYTBSRGtN
            ZkIzSjF3U2QwU0MyZkpRUldBZ0l2VU8rMUZFCjZXN0Q3Q01RWkZLR0p5TGJoOExI
            cS84RVMvUzJsOU1kT0ZYRE5Zdk1DUGcKLS0tIHpJK2UranpZaWZLeDVvUEFpcFJa
            NHNMNnZZQWp0Ylk3SDVBQjNHZWtYRjgKuyOWMgP2BzvWdIXuYFtJ3HAztLlEHY/X
            T9uWtuu+a+azpuhJ7CjhDT0tlsC7JLUj8DsbqPjev8GeB/hbL35MTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYTNidVBoaURkbE4zVW4r
            d24rSnpQcmFpWDNmNWhxNnNXWGRsUGxDckJjClNTdjJxUnhDVUdVZEtmWUg5Vi84
            YStIczFtR0lPR1ozV1dxYStYS2FKZ2sKLS0tIHY0TklBVW1Sek9sY3hZRFRab0NW
            QTVuS1l0MTg5dnVrQS9uMTJiSzA2MlEK7CXl2BKHeqDRGUl40g7qsZcJrUeqx6Wd
            5Fa8PXFOenaZrz50vBEId6jX5BEyMmxJMXFkiWnWPNu1mpcGY3j1Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T12:17:09Z"
    mac: ENC[AES256_GCM,data:sN0aK2XJM+ppa9Dd0FSEN0MtoY2/XZX88Hiq9XcMcei8cxdLFx250mXq2I7pzjglklFtcOENokjyP3HqWbK21NtjYXsxtPKIl1c5WrdthEvCKF0z/BSyfXXGOaAVQleH0tTsp2/zlnAKEXTlAyPtzpS9yZ4GbRxi/rurLypR2i8=,iv:b/Ddw9taYpZVN1U1RBAAlgEXut56Thj7Tz8dXjoAXhg=,tag:qCadJYy6dLWQ0+E/FC0Nmw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
