apiVersion: v1
kind: Secret
metadata:
  name: duckdns-environment
data:
  DUCKDNS_DOMAINS: {{ index .Values.secrets "duckdns-environment" "DUCKDNS_DOMAINS" | b64enc }}
  DUCKDNS_TOKEN: {{ index .Values.secrets "duckdns-environment" "DUCKDNS_TOKEN" | b64enc }}
