# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Bootloader.
  boot.loader.efi = {
    canTouchEfiVariables = true;
    efiSysMountPoint = "/boot/efi";
  };
  boot.loader.grub = {
    efiSupport = true;
    device = "nodev";
    enableCryptodisk = true;
    useOSProber = true;
  };

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "aesni_intel" "cryptd" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ rtl8821cu ];

  boot.initrd.secrets = {
    "/boot/keyfile.bin" = "/boot/keyfile.bin";
  };
  boot.initrd.luks.devices = {
    kang-home-nixos = {
      device = "/dev/disk/by-uuid/37edcf90-d80a-4ba4-9fb2-b07cf5561106";
      preLVM = true;
      keyFile = "/boot/keyfile.bin";
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0b10eb1b-605c-4e92-b321-0191ad3bc76b";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/3CF5-215F";
      fsType = "vfat";
    };

  swapDevices = [ ];

  networking.hostName = "kang-home-nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0f0u13.useDHCP = lib.mkDefault true;
  # Enable network manager
  networking.networkmanager.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
