apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-work
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.work.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-conf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.volumes.conf.size }}

