apiVersion: v1
kind: Service
metadata:
  name: adguardhome-external
  labels:
    component: external
spec:
  type: NodePort
  externalIPs:
    - 192.168.219.104
    - 192.168.219.114
    - 192.168.219.150
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
  selector:
    app: adguardhome
