apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: adguard-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /adguard
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-http
spec:
  entryPoints:
    - web
  routes:
    - match: (ClientIP(`192.168.219.0/24`) || ClientIP(`192.168.128.0/24`)) && PathPrefix(`/adguard`)
      kind: Rule
      middlewares:
        - name: adguard-stripprefix
          namespace: {{ .Release.Namespace }}
      services:
        - name: adguardhome
          namespace: {{ .Release.Namespace }}
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: (ClientIP(`192.168.219.0/24`) || ClientIP(`192.168.128.0/24`)) && PathPrefix(`/adguard`)
      kind: Rule
      middlewares:
        - name: adguard-stripprefix
          namespace: {{ .Release.Namespace }}
      services:
        - name: adguardhome
          namespace: {{ .Release.Namespace }}
          port: 80
  tls:
    secretName: generic-certificate
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: adguardhome-udp
spec:
  entryPoints:
    - dns-udp
  routes:
    - services:
        - name: adguardhome
          port: 53
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: adguardhome-tcp
spec:
  entryPoints:
    - dns-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: adguardhome
          port: 53
