apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: adguard-stripprefix
spec:
  stripPrefix:
    prefixes:
    - /adguard
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: adguardhome-http
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`192.168.219.150`) && PathPrefix(`/adguard`)
    kind: Rule
    middlewares:
    - name: adguard-stripprefix
      namespace: {{ .Release.Namespace }}
    services:
    - name: adguardhome
      namespace: {{ .Release.Namespace }}
      port: 80

