apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: adguard-stripprefix
spec:
  stripPrefix:
    prefixes:
    - /adguard
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-http
spec:
  entryPoints:
  - web
  routes:
  - match: ClientIP(`192.168.219.0/24`) && PathPrefix(`/adguard`)
    kind: Rule
    middlewares:
    - name: adguard-stripprefix
      namespace: {{ .Release.Namespace }}
    services:
    - name: adguardhome
      namespace: {{ .Release.Namespace }}
      port: 80

