{{ if .Values.samba.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: samba
  labels:
    app: samba
spec:
  type: {{ .Values.samba.service.type }}
  selector:
    app: samba
  ports:
  - name: smb
    port: {{ .Values.samba.service.port }}
    targetPort: 445
{{ end }}
