apiVersion: v1
kind: Secret
metadata:
  name: smb-config
  labels:
    app: samba
stringData:
  config.yml: |
    {{ .Values.secrets.config_yml | toYaml | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-env
  labels:
    app: transmission
type: Opaque
stringData:
  {{ .Values.secrets.transmission_env | toYaml | nindent 2 }}
