apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.global.sharedDataSize }}

---

{{ if .Values.transmission.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.transmission.configSize }}
{{ end }}
