{{- range $name, $value := .Values.mcp_servers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server-{{ $name }}
  template:
    metadata:
      labels:
        app: mcp-server-{{ $name }}
    spec:
      containers:
      {{- if not $value.image }}
      - name: supergateway
        image: supercorp/supergateway:latest
        args: ["--stdio", "{{ $value.command }}", "--port", "8000", "--healthEndpoint", "/healthz"]
      {{- else }}
      - name: {{ $name }}
        image: {{ $value.image }}
        command: {{ $value.command }}
        args: [
          {{- range $arg := $value.args }}
          "{{ $arg }}",
          {{- end }}
        ]
      {{- end }}
        {{- if not $value.notHaveHealthEndpoint }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
        {{- end }}
        {{- if $value.secrets }}
        envFrom:
          - secretRef:
              name: {{ $name }}-secrets
        {{- end }}
      {{- if $value.nodeSelector }}
      nodeSelector:
        {{- range $key, $val := $value.nodeSelector }}
        {{ $key }}: {{ $val }}
        {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-{{ $name }}
spec:
  type: ClusterIP
  selector:
    app: mcp-server-{{ $name }}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
{{- end }}
