apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
type: Opaque
data:
  {{- range $key, $value := .Values.librechat.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- range $name, $server := .Values.mcp_servers }}
{{- if $server.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secrets
type: Opaque
data:
  {{- range $key, $value := $server.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
