apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: librechat
type: Opaque
data:
  CREDS_KEY: {{.Values.librechat.configEnv.CREDS_KEY | b64enc}}
  CREDS_IV: {{.Values.librechat.configEnv.CREDS_IV | b64enc}}
  JWT_SECRET: {{.Values.librechat.configEnv.JWT_SECRET | b64enc}}
  JWT_REFRESH_SECRET: {{.Values.librechat.configEnv.JWT_REFRESH_SECRET | b64enc}}
  MEILI_MASTER_KEY: {{.Values.librechat.configEnv.MEILI_MASTER_KEY | b64enc}}
