{{- if .Values.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: litellm-env
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
