auth:
    - user: ENC[AES256_GCM,data:Ms8=,iv:MhUeLTlSP/xkn9XguELH0oHf+rTNVT5JjBwLpjc0pkg=,tag:jM1o0A8gt6Ph39fOYHxrrA==,type:str]
      group: ENC[AES256_GCM,data:VuU=,iv:PDhygbCMqdhz81Iqxqgkya640N2HMMWZ5MOtT8bK9hI=,tag:n2cBixII+Vet39MsoKV6yQ==,type:str]
      uid: ENC[AES256_GCM,data:1/wwuw==,iv:LOrmuRKtvgbAo3M4Uljs537zX2FaJsh91VYIzRnp8Cg=,tag:qA/iaYJCN9bEEIGn4w9OTw==,type:int]
      gid: ENC[AES256_GCM,data:T4l4ow==,iv:NATGmHSP5o4MeBLufi+humZqyunUJH4U/4OCo1l3hXw=,tag:+v/nIGCJr6z9fszrG67cKQ==,type:int]
      password: ENC[AES256_GCM,data:YUoqZmshnTLoK3g6,iv:qPlkle+GMKA7Dv/a+DzmbwL6dz1A2LYAWB8k2r2jd7w=,tag:gVhVomPBU+2b5dbwxtIyBQ==,type:str]
global:
    - ENC[AES256_GCM,data:J95ss0+L55xmSQOPfI1d,iv:fcFG54TFbWpXxIj6e7D10cUwaNIWoxKsWTtvOvXRLBI=,tag:v6hsV/YUGm9fY+fwH/UTpA==,type:str]
    - ENC[AES256_GCM,data:6mVl5RUDRpDTJ7anAkOiqw==,iv:G8Q7weiMo0x6hGM7PId+bkaUZVTfTaeoXcqzWg7UISk=,tag:uib+njQ7xr2REYrKjuhO6w==,type:str]
share:
    - name: ENC[AES256_GCM,data:GwA=,iv:rMIDWhaLGdDEwthofW4EFRONBKGjuMfboWgtZ/uTmDs=,tag:2dCx6fT3DL9QWlbYNqck7Q==,type:str]
      path: ENC[AES256_GCM,data:hgNygtsx,iv:bgvJRUfmVOfQdGrXzvZNz/+McDqZ1Gxi5LH7PLgqkeQ=,tag:nTRn5Pc3K798m5ou9aPzJA==,type:str]
      browsable: ENC[AES256_GCM,data:LyWU,iv:aXS3LlKixzDy6iLJGZRxfvEpzOTx640+mSaMg0sU7vM=,tag:aI9QV6HV7Z2ASZd/f1jbIg==,type:str]
      readonly: ENC[AES256_GCM,data:NBA=,iv:R4w9BPFNApkJHp5+7sl1J2bYXqQuKaunRdS92UZOy0c=,tag:PZdZVvEWyj9UEj0uLyTdGg==,type:str]
      guestok: ENC[AES256_GCM,data:29Q=,iv:vqt5fx1oubvG0bSbmERgBWyn5P16VGw/QAR97b5kz8A=,tag:7RqLfAyaI7RuNEtHGNj7fg==,type:str]
      validusers: ENC[AES256_GCM,data:vbA=,iv:pGcY5dHB5vYbADYcYtwvYvinaiG5v5UwfTrrEzTUtjM=,tag:dKfgI/pw949N3qVvGgytbg==,type:str]
      writelist: ENC[AES256_GCM,data:Kso=,iv:A/ypy1idiBgKizfb3Jnp9QGWqbSCF//Nn+5414EAUbQ=,tag:U3ncC0knipgBTCWyXogAEQ==,type:str]
      veto: ENC[AES256_GCM,data:9es=,iv:DQuvHPUmCSvvW/QqygOij7TiLzPoVU+EsGaaa/4iziI=,tag:DxdxztOhwu+/zSUrdD8VxA==,type:str]
      hidefiles: ENC[AES256_GCM,data:6TitdA==,iv:kfXl5um7o995amG/8MCWIFCB+RM5AjYbB+Qcq1hUmJ8=,tag:tttYbTn3BhdNe5rtkcBukw==,type:str]
      recycle: ENC[AES256_GCM,data:Ipw1,iv:YeNduAT+BVjr+yHJTYSUKpT2tmlJgY+gmJAvF7jM1Zg=,tag:8xTMIcEM8EQR0QvgX8IO8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN2FCMHlqR05ma2lpU0c2
            WkMvMElLa2xyVkJ2NGZWZDQ3RENJeDVEMlIwCkpxQ1pnVUZBdmFFSS9XaC9Ya3ds
            d1I2WXBzNmhCcWJYSEVkQW0vY1FQYkEKLS0tIEVWY09QSXlveUxnZCtmTXdLbE8z
            dEw4WGRtSzZrRk5QbEJMNG0wTjEvTWcKB/TZWuFug1pVA5J/HYwTjEOXhRRw8H+m
            +R3cCbGPNumY75Ki8m5icn6gabM4xRwlkuZvGZ/6r96CXQYPxPkR2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xf07v5cv2zdrevmv5mfwen8jhg8nu2gkl7sr0j04gdkyfqlr2fcqk9qwze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQVo4WFFxUEJDOWpZUnZz
            MFRGSitQRUhtSzJWWVE1NzJ5OE9Yd1liQUV3CklUTUM1cjh2T1I4VkZBd0kvNy9r
            N0pQMDRrZFVzSFY0YThrMUNoZW5uOFUKLS0tIE1mNk5XLy9SV2pyM0RabWdiUUU5
            VkhuM0k1SEVBc1o1SDh2TmV3ZTh0R1EKjqsKI1yFz5nGvA8yNKK2YYkU9wPS/JIN
            uv4LAJtroa/NP29Czyxe2XY6zLXiVeiH7uztb+b7wJWEu5XCdhJtWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T13:56:14Z"
    mac: ENC[AES256_GCM,data:fSFJyygnlDKkG2Lmi3T6EhtCTpbuUC3Kh8YDhkTz0psXAfXz+ykxfIRFheL4idzYQAiBgq0xTMj6DXXlpPkvaaV9bHRDmOpHXJas5Uzk5pqJxmefoP3m5zN2kJYXpjGiMyuowglcmG3yMgeujX9ZfErvSyB9Xs/eQFS+Z2bGPqI=,iv:mrOi1rBXQJvn0Fz9EXGc9FieoJJ3Co1OX+8oLvPLnnQ=,tag:BqiVnde2JyRoRFmFSpx6Rw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
