main:
    secret:
        n8n:
            encryptionKey: ENC[AES256_GCM,data:Mv3uybD+G/bl6t8wDTEM171+UjIQ+wb7DbUkEwtenb0b4Ulh5crXfHirrIpLV+oRTuC7Ehbpvo/CkTt690PWCQ==,iv:KZhOEQ/EpwJh4yWs91q/l+pSbe7cHZmRnERTQmsMBbc=,tag:WGpPt74Q+y3MJUFasfMyuw==,type:str]
        db:
            postgresdb:
                password: ENC[AES256_GCM,data:l9un1MchRJOZr/493SBtVc+CL0DLgOES6KGfdPi/P7hbkqNQhTYljWNVuV7aQQIgY5ZuJySBadENEgzJZOebQg==,iv:K/8psMvwgeJJ+JimLdN0//HwFBjw7cQcgUrRw4cMbkM=,tag:ElJFOFo7bFvUtO/owWB45A==,type:str]
auth:
    password: ENC[AES256_GCM,data:c0V5qxeXJGL7N2pbmsb5jsI/2E1YM9uVDM/qeZVIjUzhHftDdoor+qAVAdD6YStdi8tuqSjBYurpdP5rvOkj6w==,iv:IUcLDFUCoLa/N8ECpedivs07+WaDvxEpWrBQEJX6bYg=,tag:/yEuHC/GdlES9WfhUCaUxw==,type:str]
sops:
    age:
        - recipient: age1wjnx0ggpvkk9aufyu2juzc7fvlgcefxx5ngn5hsae5n5vl47fcaqzstuf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZXNtR1h1VWhUaTN0RmIr
            UlQ0UGRaRStwZGNuWHZqWEhHQlpXdzV5YjJRCkQ1UzJFaFJPNng2M2hLdWJyME9q
            QXAyQXlCc3hXdTY0UGpGK0VqNzFpUVEKLS0tIExTbkxoYStqNXQrcVhkc0xuQXNO
            aGE2di85RmhkZ3R4MzJ0VkQwMmRNa0EKBTHVXY4B1ld5AjsDGwRPRq6bQN1+19Ch
            4kxRys4Ty4vg2To0NmPcvaQVanWec9APVuvTe7j+mudruMYyY5g2oA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eyjyp4n5ke066nkgcxkqmkzl50nlwkdufsm2qzz5rfvc7peelc5qlnufz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcVNiVEhGSjZVaUNieHhW
            cklTU1kxZGs5TzdSYVExZllxQkdUUURiWlVjCnFiUWVOUkFJWWNIVUtjR3c4TCtm
            KzY0a1RqZ3Y3OFlJM1g2N2c4L09BOEkKLS0tIGhPMDlwMXIySS9NUVJMNndrZVdp
            cSs0NjdFMHBqdGNqMXJEYUh0YktOUjgK9NloCLmZMLM+d9+3TgIHw6uD+BC+Mnj+
            8q1xhD/lIA3b7b5oKRVDca42qC/Wo/+TCKTfHe1V3LGxgP+wMGU08w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMU52WTM0bFlVZVFMbVox
            VnNJVXNPZUE0L2dacnJoaG9DSjRjV0Yzd2lvClI1dGRIdCs4bzd3SUNaMTNDNEpN
            THp2d3ZYUmlHMVBJa1I1eVErcXNpbFUKLS0tIHc3akJhb0V1MjFkeTV3QU5wVkFS
            QUtWN25EWEt4WmF4Nm40alFQK25jajQKkapRiZe7/cosY74a5bVS5yayImu9j1C/
            cJ1DBPI3cHQP8/wMEUnfDq6TjoT5CP9iVdOqw0TEGn+y78OKxL1mDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T14:45:17Z"
    mac: ENC[AES256_GCM,data:ojOs2VfyA4hc0op313B1/zYYg4MSMLJwarrLB118vTB4c2CpiZ3iNHoDDyYx54PrMz2QkpsB1sTq5vw5no2OE6wijzdHUUEoDHs8DamrfPuYMdltDaJvuLBih28T1rB91b0h9cpRvFQoqL91GI2blFRZr3EJBp+g0PG+jjpFXGI=,iv:VgAxumtAQhVxYWNZynPpkSQFMmwXeSXOqWiZ92AbEts=,tag:NzKomIBL9t/mJ29D/O3FvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
