image:
  pullPolicy: Always
  tag: latest

main:
  config:
    node:
      function_allow_builtin: "*"

  persistence:
    enabled: true
    type: dynamic
    storageClass: "nfs-client"
  service:
    type: ClusterIP
    port: 80

  extraEnv:
    N8N_SSRF_PROTECTION_ENABLED:
      value: "true"
    N8N_SSRF_ALLOWED_IP_RANGES:
      value: "10.0.0.0/8"
    N8N_PORT:
      value: "5678"
    N8N_HOST:
      value: "0.0.0.0"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kang-stay-gmk
                - kang-rpi4
