secrets:
    hostname: ENC[AES256_GCM,data:5eQ5UDr6eZ4a5YLIbVtPqmE=,iv:aiOR5kYeAXlKcYGnBQVwCAWxtstFOrNHbxwRafC9HP4=,tag:bBRnKgAQULWz3PvICFmx9w==,type:str]
    env:
        LITELLM_MASTER_KEY: ENC[AES256_GCM,data:MO/e6mTQlKWa5X1akmpsyZ4evc6y70CkOii7nvfw/5n9xuu5dXpI3izhR2eTLHM=,iv:Y2P8QE97DPR5HZgOJEUcKZwYA0252890pIdbRhJ/3Ws=,tag:N8nHmQxLqyIuO7bMtF4aDQ==,type:str]
        DATABASE_URL: ENC[AES256_GCM,data:MzLPaQO3q+DabiSpQRZfK6To7QPRri+WBY8kKMeFzobzMjMdgiTKS9sQSl239+Qxb2PhthDENCL2WMLj+rqNzNCHkpVQN7pSmbgjjHHWAM0FtYiU+puWgs3+ANsfilFW2oQfO56SQ+HW7fNA8T4=,iv:CNVXfdig6GGpTaa35tRNa8+oekZ0La1/NvckP9gVhjg=,tag:jFNc0JMJ3FX3V3+Cf89uGw==,type:str]
auth:
    password: ENC[AES256_GCM,data:tuPtTjSypVr2HSqiFq31DLOTLKplWm4Ykl+pmS1vxkMF6NgoZ/zaDm93ft8=,iv:f8GVAwEbkun5rqFZZF8dUZyB7IINF+l/cUbNU4XgsIA=,tag:o9cjGvRdd5qTdfUShiOw6A==,type:str]
sops:
    age:
        - recipient: age1wjnx0ggpvkk9aufyu2juzc7fvlgcefxx5ngn5hsae5n5vl47fcaqzstuf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQzVCQWM2eDFlNFZ5clVL
            ZGkzem5uQUhHSzNIaVk2clRhY1R2NVdhblQwCkRJOGdldnpBUUlvUDc3YVh6UVk5
            RzZjWEdkYVRGS0xDR3p2ODR4QTgrcncKLS0tIE1LRnFMY1hZMDRVdEJtam1wMks2
            ZWkzVlJtMjJVcDhqS2ZqVnBQejhNa1UKBaLLkha8RrVGtkXssg/T5YAQ/J6WNEaY
            fl00cI0mXZeKHfdC2pw4OZYxBpVXJa6vq8hUKnOD94bmGz3Op7Eivg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eyjyp4n5ke066nkgcxkqmkzl50nlwkdufsm2qzz5rfvc7peelc5qlnufz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQlNyRytsQTVBaVNlVDRs
            MmNLakkwTVNHWWxvaVFMa0Ewbm5NcjhBWWdnCllNTDYwcDBYV2NLV0g2dXVwNUxt
            d2tJdUJkQ3BnbEhNT1BvV21Kb2FGcTgKLS0tIC9OVy9kSG9RQkNBQjNUUUlxZjZG
            WVJrMnRnMHRZN0N2TFgvd3BzUEdCcG8K8ZlWs9Fi4KMV4aZ40WWGwfY6SvSsSOF1
            Yn81nf9c8nFK1OIt6eDKsLv/jKZr1JNBNREhCcTS7YMaVJ4rVQqruw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVUVKWjFYanVITk5id2JO
            dHlLb0RwYmtDNklrQWpxTW54WFU4MVJsMXlFCnYyN3AwQitqOHdYbE9FSDVGWDZ4
            bnBVZkh0Y2pjekNieVBMM0tnVlVTNDQKLS0tIHcydUN6czc2MTlaMlpvNWE3RVlo
            aTdsb0cxbzBvSUUvVk5EcnlKRDV2LzQKgJprG5qcUxAeWA1kfzLOz65ViNFcbnFf
            cukaVMRLCpWmjr9Wvz8gT0ybe+kRJdbGOJlGXoNqewUuse3vgGcp/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T15:50:02Z"
    mac: ENC[AES256_GCM,data:wUsXbm49GZ5kaG+nusuv71zA5qYbkICRGntUzcXaHtZe79NyFKI8m7LHw2EBAG/2Gyvk9P8dMLqVvfyA/we+ix3+Xxa5cRFYBVTIgKbivT6Ji1k7dxATQ1bbpWL/xrudPRYhZcGsqASC4P5ttwzFvwRjw2fSL0fQDiFSDFcciZY=,iv:fs9fEGne18PFEy8N0IvtjF9hHSgh4WJMTDEvy3jf9/Y=,tag:btGSjfmxG0K+SrzcvuQ+/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
