apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-file-server
spec:
  selector:
    matchLabels:
      app: static-file-server
  template:
    metadata:
      labels:
        app: static-file-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
          - containerPort: 80
        volumeMounts:
          - name: static-files
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
      - name: static-files
        secret:
          secretName: serving-files
  replicas: 1
