apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: static-file-server
spec:
  entryPoints:
    - web
  routes:
    - match: ClientIP(`192.168.219.0/24`) && Host(`{{ .Values.secrets.hostname }}`) && (!HeaderRegexp(`Cookie`, `app_route`) || PathPrefix(`/set-route.html`))
      kind: Rule
      services:
        - name: static-file-server
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: static-file-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: ClientIP(`192.168.219.0/24`) && (!HeaderRegexp(`Cookie`, `app_route`) || PathPrefix(`/set-route.html`))
      kind: Rule
      services:
        - name: static-file-server
          port: 80
  tls:
    secretName: generic-certificate
