apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
data:
  config.json: |
    {{ .Values.mcpo.config | toJson | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcpo
  template:
    metadata:
      labels:
        app: mcpo
    spec:
      containers:
        - name: mcpo
          image: ghcr.io/open-webui/mcpo:git-a5f6222
          args: ["--config", "/config/config.json"]
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: mcpo-config
---
apiVersion: v1
kind: Service
metadata:
  name: mcpo
spec:
  selector:
    app: mcpo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
