apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui-http
spec:
  entryPoints:
    - web
  routes:
    - match: (ClientIP(`192.168.219.0/24`) || ClientIP(`192.168.128.0/24`)) && HeaderRegexp(`Cookie`, `app_route=open-webui`)
      kind: Rule
      services:
        - name: open-webui
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: (ClientIP(`192.168.219.0/24`) || ClientIP(`192.168.128.0/24`)) && HeaderRegexp(`Cookie`, `app_route=open-webui`)
      kind: Rule
      services:
        - name: open-webui
          port: 80
  tls:
    secretName: generic-certificate
