secrets:
    LITELLM_API_KEY: ENC[AES256_GCM,data:CbdoIYiQrQbR62V5s2xW7jKBmX+NEV2r7w==,iv:NY8w6GvsJzrD4OXVaTzi9HmPwNU0DWIGmEQn2xlNEqM=,tag:fit3XEoj567IMea6v1s53Q==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:enmaU4cnQOVxYQpE7Bu4FP0sS4G87FRhC8t1C288dgeKNqhsvCIfDxBxQVivfV+xIH8BFGlnIZnxFapKBetGmJiIBaUyTqEG,iv:1Hk3ynbMsYGyXF9U/seGZCc78bW2Fc2c8Mg0svw/90E=,tag:7mkRPazJCEYCw9Fm3YENqw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:+NzudOfxkOt8naOWSyzXF8NH6HqRBHFEGPAuLa2Ml83h0X6MIVz1mfFYg1xrqQ==,iv:PLiwerIM64qSSxy6d5LkO6N8DCKXI9iP+AqRrTc8wSE=,tag:+9FbKaWWoYk5B/pqN90oIg==,type:str]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:49JBzlCNCvkRVL3gASuteIM/ZGS79aMG8oF5gygIMoQ=,iv:GBo8v9tzDSdR0NJWKtBz+EsJu7wwXORfNga3exwNHGw=,tag:NIymj24Z/BwMGbCRhM+NVQ==,type:str]
env:
    WEBHOOK_ENABLED: ENC[AES256_GCM,data:5LqE2w==,iv:F95yDw2iP0A6kdhXQ05bacfe6f/SfGnuy3hiSTj0GjU=,tag:HFMW0Z8+YxydKP0vFPYQsA==,type:bool]
    WEBHOOK_PORT: ENC[AES256_GCM,data:vgtgQg==,iv:bIg5BFYRdDQT/vGfGJKUtXw6Pzh0sb9vi2++Fp/ecbU=,tag:CjZ0GkfTgvgHCZL5H8402w==,type:int]
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:Z5QFjw==,iv:tyVxeSJNukLEXeqlptYGE3EZdPELi6BjhcvY9fa/3AE=,tag:2e4Wsh9eK0Lg9PH6FLSMBQ==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:RFRZgjdN/50XfX3bhDTE+Xb1TaTH,iv:vbJMB9DUDOvzk2eSB5Wtp0Ckr7DkOB6PSAlPKzZfLXY=,tag:XHdRMtnyr9So0suHVq/rsQ==,type:str]
    TELEGRAM_ALLOWED_CHATS: ENC[AES256_GCM,data:kkW8gvR/og9bM4qmQY4=,iv:um7Lgai2mvQMF3UDr+HviQ9xiB78ldIr9zlprv2wqwY=,tag:U1HJfCoY9/aXw3NYDCrPew==,type:str]
    TELEGRAM_GROUP_ALLOWED_CHATS: ENC[AES256_GCM,data:GSpE4mKvMuBhf3BfCYQ=,iv:L/Lj8Zbio4uVlnT36+O/uZzL8vmSkzzLR5V1zT29fRs=,tag:/BWprrUkNGdBdARise+AEQ==,type:str]
    TELEGRAM_GROUP_ALLOWED_USERS: ENC[AES256_GCM,data:Z/NGqS+MMedK9GkoGoQB4W81q9AP,iv:DtIdw2gzfS7xzKTvOaPBZIFHQNBfvHBhvtcl7bMj+T4=,tag:8gEQN2ZczsL27uxx4QshSA==,type:str]
    TELEGRAM_OBSERVE_UNMENTIONED_GROUP_MESSAGES: ENC[AES256_GCM,data:cpKwZA==,iv:mHU42ipo6pxZ5mWhVxXcJWenmV0G3vOszgnOITDXzRM=,tag:nmYB4IgWwUah4l/mJPLH8w==,type:bool]
sops:
    age:
        - recipient: age1wjnx0ggpvkk9aufyu2juzc7fvlgcefxx5ngn5hsae5n5vl47fcaqzstuf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeTJLK0NWR01nZlNBY2dD
            N09iUnduM1JDeUEvcVpOMUhEU3ZkZkxtNXdzCmdXRjRjRmhpaFUrYVY2MUwwMG4z
            RVluMGk4OW8wMWREQ1duUXdtamxGRVEKLS0tIDZxUk1ZNk5uRVFMV0dXYWJRR1Nj
            Ni9YUUI4ekhPeStuOFJ1UnpVdWlhNncK0dkIqUv6fNQO+WyG5DmJThMarzu7KycL
            7FyU8+dTuttUqTcZ2h+4dt6hZDtokdrO/RMR9dbAr2dY3KfcjrnMwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eyjyp4n5ke066nkgcxkqmkzl50nlwkdufsm2qzz5rfvc7peelc5qlnufz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRjRHazlOL3kyZVl6OG1L
            R1NtaHlFSkNXeFVYc0NCRmJCVmNSbWtmM1FBCjhpVVkxbHdQdzZrblBIQkNQNmNs
            eWg0bk40cll3S2gvS2crTmRwaDZxdnMKLS0tIE9sNGkxd3Q4TURxN0RsL1QrWXBK
            dFRSQy95ZUxuYXB1YUZYYlF3aGNzeEEKbV0DCQvRR19Qggb5C1dWfyKAaUr2Bjcy
            tGGTlpSOB9RkrviBGc5Zic42PRLCcsFNk1Ad/4fGRUxeNsEIgU2eAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNzAxcCtxdXB3ZldEZEh5
            c3hRU3p5dEU4bjltanRFWHRQT0dhZlZyN3hJCkVmbGdqZ0Q1N2ZhWjgvTWdqTzFD
            TFBzOFE4empvQW1kVm5zTm94RUczWVEKLS0tIHN5bWsyZ25vb1J5eDA0ckk0cmg1
            d2g1REdabTFnT1Q3ZzJoRFR2Uk15bmsKQNaayGLtau8fv6zOmHOpDhFJwkbABfMB
            uzY4GeqeMDxox77IyXxQQOeMNEGNnPTntdRuNY3xY00HVzszoj9ejA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T09:31:32Z"
    mac: ENC[AES256_GCM,data:yx9qOmvsRLQcFILIUQxU5KpL50u9XUWjqTxZ8VaRzMdVFsLJC5fK1wUmPkkncmh2v+XbPcBZpAcHsKVjedEr8FauNszRyUnlZS6wPUs1zS1BB3JQmWiL0kGRe7eUgDBLT4S5W8uFIzty1vw1qnskr/vuuWHti+M3YaLAufnwAAw=,iv:5OMmr2Ab4IPXfOBt1oFK5WrMC/h/bOxbeGN4G3ouAeQ=,tag:Ry3EKYx4hmn+VbT0JElBEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
