secrets:
    OPENAI_API_KEY: ENC[AES256_GCM,data:dnhU6dF6MaCQe6jZpbrFq/0C85xbQUxNnQ==,iv:gjoHiblZ/3rQFroTvTlLjp0CvMMVHUvW//WGKyumC1Y=,tag:1F4vViMPY1lzt+h0+3uQ+g==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:enmaU4cnQOVxYQpE7Bu4FP0sS4G87FRhC8t1C288dgeKNqhsvCIfDxBxQVivfV+xIH8BFGlnIZnxFapKBetGmJiIBaUyTqEG,iv:1Hk3ynbMsYGyXF9U/seGZCc78bW2Fc2c8Mg0svw/90E=,tag:7mkRPazJCEYCw9Fm3YENqw==,type:str]
env:
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:Z5QFjw==,iv:tyVxeSJNukLEXeqlptYGE3EZdPELi6BjhcvY9fa/3AE=,tag:2e4Wsh9eK0Lg9PH6FLSMBQ==,type:str]
sops:
    age:
        - recipient: age1wjnx0ggpvkk9aufyu2juzc7fvlgcefxx5ngn5hsae5n5vl47fcaqzstuf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeTJLK0NWR01nZlNBY2dD
            N09iUnduM1JDeUEvcVpOMUhEU3ZkZkxtNXdzCmdXRjRjRmhpaFUrYVY2MUwwMG4z
            RVluMGk4OW8wMWREQ1duUXdtamxGRVEKLS0tIDZxUk1ZNk5uRVFMV0dXYWJRR1Nj
            Ni9YUUI4ekhPeStuOFJ1UnpVdWlhNncK0dkIqUv6fNQO+WyG5DmJThMarzu7KycL
            7FyU8+dTuttUqTcZ2h+4dt6hZDtokdrO/RMR9dbAr2dY3KfcjrnMwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eyjyp4n5ke066nkgcxkqmkzl50nlwkdufsm2qzz5rfvc7peelc5qlnufz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRjRHazlOL3kyZVl6OG1L
            R1NtaHlFSkNXeFVYc0NCRmJCVmNSbWtmM1FBCjhpVVkxbHdQdzZrblBIQkNQNmNs
            eWg0bk40cll3S2gvS2crTmRwaDZxdnMKLS0tIE9sNGkxd3Q4TURxN0RsL1QrWXBK
            dFRSQy95ZUxuYXB1YUZYYlF3aGNzeEEKbV0DCQvRR19Qggb5C1dWfyKAaUr2Bjcy
            tGGTlpSOB9RkrviBGc5Zic42PRLCcsFNk1Ad/4fGRUxeNsEIgU2eAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j96268thuepkcgmxcnhaeedfamdwum7lcjx0x62u84uqjw9099ysqqphw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNzAxcCtxdXB3ZldEZEh5
            c3hRU3p5dEU4bjltanRFWHRQT0dhZlZyN3hJCkVmbGdqZ0Q1N2ZhWjgvTWdqTzFD
            TFBzOFE4empvQW1kVm5zTm94RUczWVEKLS0tIHN5bWsyZ25vb1J5eDA0ckk0cmg1
            d2g1REdabTFnT1Q3ZzJoRFR2Uk15bmsKQNaayGLtau8fv6zOmHOpDhFJwkbABfMB
            uzY4GeqeMDxox77IyXxQQOeMNEGNnPTntdRuNY3xY00HVzszoj9ejA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T15:34:26Z"
    mac: ENC[AES256_GCM,data:Mv14UFbJIOC76jypuL65n0HvBkvdVZAx8hty/U4NXx3E6s6zgp/qbbTBSeGS8J7vr1yxycwv/vSw0vdqatx3vtYveSdwpQETrL8TZBC9G5m4rEn1cuo/tjjmMJ7Pqabwe5D/sYh2hx8HVSaeEwLOteJgyBPM5C9kOahOz+zZ0Po=,iv:/SWAXu6aJlVbqTlXPcwvsONwPfHEBGuuQawlHT0YYi4=,tag:uONQ7JA9GisqYQklRRgw0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
