
persistence:
  size: 10Gi
  storageClass: "nfs-client"

ollama:
  enabled: false

extraEnvFrom:
  - secretRef:
      name: open-webui-secret-env

mcpo:
  config:
    mcpServers:
      mcp-youtube-transcript:
        command: "uvx"
        args: ["--from", "git+https://github.com/jkawamoto/mcp-youtube-transcript", "mcp-youtube-transcript"]
